### ISSUE TITLE
Cannot figure this out...

### ISSUE THREAD

**Issue by bensullivan8** [bensullivan8/more-than-just-datum#1]
Hi Christina,
I'm having a lot of trouble with this one. Mainly the grids and unit sizes I think, but also with the scrollable table.
Am I missing something with the grid and units to make the search bar snap up beside the logo at larger sizes? Same with the _Nearest playground_ and the _Playground in the city_ becoming side by side at larger sizes. I just don't understand what I'm doing wrong and it's stressing me out.
Lastly, the scrollable table just scrolls the whole page to the side and I'm fairly certain that's not what it's supposed to do. Any suggestions?

Thanks.
@muxlowc

**Comment by muxlowc** [comment]
@bensullivan8 hey, so it looks like you were missing your unit sizings. 

I attached a screenshot below with the outline you should have. You seem to have broken the section down into the units where needed, but without the sizing added, it won't really work.

<img width="653" alt="Screen Shot 2020-04-20 at 8 41 37 AM" src="https://user-images.githubusercontent.com/59422623/79752906-00278b00-82e3-11ea-8c10-cbe8eebb0d48.png">
(Also just fyi, you don't need a header for this one specifically, just those two divs with a grid+2 units inside them)

And to make the table scrollable, what you need to do is add the "scrollable" class to the div surrounding your table, and then in your css you need to add a min-width - meaning that your table wont get any smaller than that number, but if your browser is smaller than that, then it will become scrollable. Hope that makes sense!

```
<div class="table-wrapper scrollable">
        <table class="push-0">
          <caption class="bold not-italic giga push-1-2">Playgrounds in the city</caption>
          <thead>........
```

.table-wrapper table {
  min-width: 45em;
}

**Comment by bensullivan8** [comment]
The table is scrollable now but the sizing is not working...
I don't know if it's something to do with how I configured the CSS or what I'm doing wrong with the HTML. I tried these unit sizing options before I submitted an issue but deleted them because they weren't working. 
The worst part is knowing something is wrong but not knowing what it is.

Also, markbot tells me this...
<img width="500" alt="Screen Shot 2020-04-20 at 3 48 46 PM" src="https://user-images.githubusercontent.com/55108838/79793374-739abe00-831e-11ea-8879-1b4df9b2ef18.png">
And I have no idea what it's talking about.

What a mess. Sorry.
@muxlowc

**Comment by muxlowc** [comment]
@bensullivan8 
So it looks like you tried to add in another body tag - remember that `<body>` doesn't mean the same thing as `<main>` - the body tag is basically just saying "code goes in here" and head tag is basically saying "any meta data and linked files go here"

so a few things I noticed - 1) you didn't have a form tag wrapping around your input, 2) you are allowed to put an image inside of a label, which is where I moved the icon (you main need to add a left padding to the icon in your main.css still) 3) Just a few classes were just in the wrong spot - so close though.. Here's what I got so far which should help!

```
<div class="header grid grid-middle">
  <div class="unit [ xs-1 s-1 m-1-3 l-1-4 ]">
    <h1 class="logo push-0">
      <img class="img-flex" src="images/logo.svg" alt="Playground Finder">
    </h1>
  </div>

  <div class="unit [ xs-1 s-1 m-2-3 l-3-4 ]">
    <form class="relative" action="#">
      <label class="search-icon icon i-18 pin-lc" for="find" title="Search"><img src="images/search.svg" alt="Find"></label>
      <input type="text" id="search" required>
    </form>
  </div>
</div>
```

As for the second grid, you will want the items on the left side to actually be a list (it's technically listing off the closest parks), so Heres some to start off:

```
<ul class="near-list list-group push-0">
        <li class="card island-1-2 push-1-2">
          <h3 class="mega push-0">373</h3>
          <dl class="list-group-inline push-0">
            <dt class="push-0 italic milli">Distance</dt>
            <dd class="push-0">0.75 km</dd>
          </dl>
.......
```

and remove the 100% width on your "nearest-wrap" class - that's what's making your unit not be 1/4, because it's being forced to be 100% width 

Hope that helps!

**Comment by bensullivan8** [comment]
Hallelujah! Got it. 
Thank you for your assistance!
@muxlowc
